build-dockeRs:
	@echo "Build GNU-R 3.6.1 on Arch Linux Docker image"
	docker build -t ismailsunni/gnur-archlinux .

run-dockeRs:
	@echo "Run GNU-R 3.6.1 on Arch Linux"
	docker run -it --rm ismailsunni/archlinux

pull-dockeRs:
	@echo "Pull GNU-R 3.6.1 on Arch Linux from Docker Hub."
	docker pull ismailsunni/gnur-archlinux
