run-dockeRs:
	@echo "Run pqR 2019-02-19 on Debian Docker container"
	docker run --rm -it nuest/pqr:2019-02-19

shell-dockeRs:
	@echo "Run shell pqR 2019-02-19 on Debian Docker container"
	docker run -it --rm nuest/pqr:2019-02-19 /bin/bash

pull-dockeRs:
	@echo "Pull pqR 2019-02-19 on Debian Docker image."
	docker pull nuest/pqr:2019-02-19
