# run-dockeRs:
# 	@echo "Run GNU-R 3.6.1 on Docker with Geospatial packages"
# 	docker run -it --rm rocker/geospatial:3.6.1 R

build-dockeRs:
	@echo "Build GNU-R 3.6.1 on Docker with Geospatial packages"
	docker build -t ismailsunni/gnur-ubuntu-geospatial .

run-dockeRs:
	@echo "Run GNU-R 3.6.1 on Docker with Geospatial packages"
	docker run -it --rm ismailsunni/gnur-ubuntu-geospatial R

pull-dockeRs:
	@echo "Pull GNU-R 3.6.1 on Docker with Geospatial packages."
	docker pull ismailsunni/gnur-ubuntu-geospatial
