build-dockeRs:
	@echo "Build GNU-R 3.6.1 on Fedora Docker image"
	docker build -t ismailsunni/gnur-fedora .

run-dockeRs:
	@echo "Run GNU-R 3.6.1 on Fedora"
	docker run -it --rm ismailsunni/gnur-fedora

pull-dockeRs:
	@echo "Pull GNU-R 3.6.1 on Fedora from Docker Hub."
	docker pull ismailsunni/gnur-fedora

shell-dockeRs:
	docker run -it --rm ismailsunni/gnur-fedora /bin/bash

